language: go
sudo: false
go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - tip

env:
  jobs:
    - GOFLAGS: ""
    - GOFLAGS: "-trimpath"

before_install:
  - go get github.com/mattn/goveralls

script:
  - goveralls -service=travis-ci
