on:
  push:
  pull_request:
    types: [synchronize]
  schedule:
    - cron: "0 0 1,11,21 * *"
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.15.x, tip]
        go-flags: ["", "-trimpath"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        env:
          GOFLAGS: ${{ matrix.go-flags }}
        run: go test ./...
